name: publisher

on: [push, pull_request]

jobs:
  publisher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      - name: Install packages
        run: yarn install
        working-directory: ./frontend

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
